Minsal\CoreBundle\Entity\ConsumoAlmacen:
    type: entity
    table: consumo_almacen
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaMovimiento:
            type: date
            nullable: false
            column: fecha_movimiento
        ctlMecanismoid:
            type: bigint
            nullable: false
            unsigned: false
            default: '1'
            column: ctl_mecanismoid
        ctlExistencia:
            type: bigint
            nullable: false
            unsigned: false
            column: ctl_existencia
        cantidadConsumoAlmacen:
            type: float
            nullable: false
            precision: 10
            scale: 0
            default: '0'
            column: cantidad_consumo_almacen
        userIdSchema:
            type: bigint
            nullable: false
            unsigned: false
            column: user_id_schema
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    lifecycleCallbacks: {  }
