Minsal\CoreBundle\Entity\ConsumoAlmacen:
    type: entity
    table: consumo_almacen
    indexes:
        IDX_1576410846F39AED:
            columns:
                - ctl_mecanismoid
        IDX_157641082D46D110:
            columns:
                - ctl_existencia
        IDX_157641089E59795B:
            columns:
                - user_id_schema
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaMovimiento:
            type: date
            nullable: false
            column: fecha_movimiento
        cantidadConsumoAlmacen:
            type: float
            nullable: false
            precision: 10
            scale: 0
            default: '0'
            column: cantidad_consumo_almacen
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        ctlMecanismoid:
            targetEntity: CtlMecanismo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_mecanismoid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlExistencia:
            targetEntity: CtlExistencias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_existencia:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
