Minsal\CoreBundle\Entity\CtlComponente:
    type: entity
    table: ctl_componente
    indexes:
        FKI_componente_rol:
            columns:
                - role_registra_componente
        IDX_6442E5969E59795B:
            columns:
                - user_id_schema
    uniqueConstraints:
        ctl_componente_nombre_componente_key:
            columns:
                - nombre_componente
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreComponente:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_componente
        presicionComponente:
            type: smallint
            nullable: false
            unsigned: false
            default: '3'
            column: presicion_componente
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        roleRegistraComponente:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_registra_componente:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        insumo:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: componente
            joinTable:
                name: componente_insumo
                joinColumns:
                    -
                        name: componente_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: insumo_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
