Minsal\CoreBundle\Entity\CtlConsumo:
    type: entity
    table: ctl_consumo
    indexes:
        fki_fkctl_consumo_existencia:
            columns:
                - ctl_existencia
        IDX_285219DC46F39AED:
            columns:
                - ctl_mecanismoid
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaConsumo:
            type: datetime
            nullable: false
            column: fecha_consumo
        cantidadConsumo:
            type: bigint
            nullable: false
            unsigned: false
            column: cantidad_consumo
        registroSchema:
            type: datetime
            nullable: false
            column: registro_schema
        userIdSchema:
            type: bigint
            nullable: false
            unsigned: false
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: ip_user_schema
    manyToOne:
        ctlExistencia:
            targetEntity: CtlExistencias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_existencia:
                    referencedColumnName: id
            orphanRemoval: false
        ctlMecanismoid:
            targetEntity: CtlMecanismo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_mecanismoid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
