Minsal\CoreBundle\Entity\CtlConsumo:
    type: entity
    table: ctl_consumo
    indexes:
        fki_fkctl_consumo_existencia:
            columns:
                - ctl_existencia
        IDX_285219DC46F39AED:
            columns:
                - ctl_mecanismoid
        IDX_285219DC9E59795B:
            columns:
                - user_id_schema
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaConsumo:
            type: datetime
            nullable: false
            column: fecha_consumo
        cantidadConsumo:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: cantidad_consumo
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        ctlExistencia:
            targetEntity: CtlExistencias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_existencia:
                    referencedColumnName: id
            orphanRemoval: false
        ctlMecanismoid:
            targetEntity: CtlMecanismo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_mecanismoid:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
