Minsal\CoreBundle\Entity\CtlExistencias:
    type: entity
    table: ctl_existencias
    indexes:
        IDX_69499BED05C792B:
            columns:
                - ctl_insumoid
        IDX_69499BE7B62918:
            columns:
                - ctl_establecimientoid
        IDX_69499BE58E7D5A2:
            columns:
                - movimiento_id
        IDX_69499BE9E59795B:
            columns:
                - user_id_schema
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaRegistro:
            type: datetime
            nullable: false
            default: now
            column: fecha_registro
        cantidadExistencia:
            type: float
            nullable: false
            precision: 10
            scale: 0
            column: cantidad_existencia
        fechaCaducidad:
            type: date
            nullable: true
            column: fecha_caducidad
        loteExistencia:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: lote_existencia
        fechaExistencia:
            type: date
            nullable: false
            column: fecha_existencia
        almacenFarmacia:
            type: boolean
            nullable: false
            column: almacen_farmacia
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        ctlInsumoid:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_insumoid:
                    referencedColumnName: id
            orphanRemoval: false
        ctlEstablecimientoid:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                ctl_establecimientoid:
                    referencedColumnName: id
            orphanRemoval: false
        movimiento:
            targetEntity: CtlMovimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                movimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
