Minsal\CoreBundle\Entity\CtlGrupo:
    type: entity
    table: ctl_grupo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreGrupo:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_grupo
        detalleGrupo:
            type: text
            nullable: true
            length: null
            fixed: false
            column: detalle_grupo
        grupoId:
            type: bigint
            nullable: true
            unsigned: false
            column: grupo_id
        registroSchema:
            type: datetime
            nullable: true
            default: '(now())::timestamp(0) without time zone'
            column: registro_schema
        detalleSchema:
            type: text
            nullable: true
            length: null
            fixed: false
            default: 'Agregado antes de gestor de maestros'
            column: detalle_schema
        userIdSchema:
            type: bigint
            nullable: true
            unsigned: false
            default: '(1)::bigint'
            column: user_id_schema
        ipUserSchema:
            type: string
            nullable: true
            length: null
            fixed: false
            default: 0.0.0.0
            column: ip_user_schema
        estadoSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: estado_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
        suministroId:
            type: bigint
            nullable: true
            unsigned: false
            column: suministro_id
        codigoGrupo:
            type: bigint
            nullable: true
            unsigned: false
            default: '0'
            column: codigo_grupo
    lifecycleCallbacks: {  }
