Minsal\CoreBundle\Entity\CtlIndicadores:
    type: entity
    table: ctl_indicadores
    indexes:
        IDX_779BFEB8CE208F97:
            columns:
                - insumo_id
        IDX_779BFEB89E59795B:
            columns:
                - user_id_schema
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        insumo:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                insumo_id:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
