Minsal\CoreBundle\Entity\CtlMecanismo:
    type: entity
    table: ctl_mecanismo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreMecanismo:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: nombre_mecanismo
        manualMecanismo:
            type: integer
            nullable: false
            unsigned: false
            column: manual_mecanismo
    lifecycleCallbacks: {  }
