Minsal\CoreBundle\Entity\CtlRol:
    type: entity
    table: ctl_rol
    uniqueConstraints:
        un_nombre_rol:
            columns:
                - nombre_rol
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreRol:
            type: string
            nullable: false
            length: 50
            fixed: false
            column: nombre_rol
    manyToMany:
        acceso:
            targetEntity: CtlAcceso
            cascade: {  }
            mappedBy: rol
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
