Minsal\CoreBundle\Entity\CtlSuministro:
    type: entity
    table: ctl_suministro
    indexes:
        FKI_suministro_registra:
            columns:
                - role_registra
    uniqueConstraints:
        ctl_suministro_nombre_suministro_key:
            columns:
                - nombre_suministro
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreSuministro:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_suministro
        registroSchema:
            type: datetime
            nullable: true
            default: '2017-02-26 21:29:15.600166'
            column: registro_schema
        enableSchema:
            type: integer
            nullable: true
            unsigned: false
            default: '0'
            column: enable_schema
    manyToOne:
        roleRegistra:
            targetEntity: CtlRol
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role_registra:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
