Minsal\CoreBundle\Entity\CtlTipoMovimiento:
    type: entity
    table: ctl_tipo_movimiento
    uniqueConstraints:
        ctl_tipo_movimiento_nombre_movimiento_key:
            columns:
                - nombre_movimiento
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombreMovimiento:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: nombre_movimiento
        descripcionMovmiento:
            type: text
            nullable: true
            length: null
            fixed: false
            column: descripcion_movmiento
        agregaMovimiento:
            type: integer
            nullable: true
            unsigned: false
            column: agrega_movimiento
    lifecycleCallbacks: {  }
