Minsal\CoreBundle\Entity\FosUser:
    type: entity
    table: fos_user
    indexes:
        IDX_957A647971B61351:
            columns:
                - establecimiento_id
    uniqueConstraints:
        uniq_957a647992fc23a8:
            columns:
                - username_canonical
        uniq_957a6479a0d96fbf:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        fullname:
            type: string
            nullable: true
            length: null
            fixed: false
    manyToOne:
        establecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                establecimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
