Minsal\CoreBundle\Entity\HistoricoCuadroBasico:
    type: entity
    table: historico_cuadro_basico
    indexes:
        IDX_C2960F83CE208F97:
            columns:
                - insumo_id
        IDX_C2960F8371B61351:
            columns:
                - establecimiento_id
    id:
        fechaCuadroBasico:
            type: datetime
            nullable: false
            id: true
            column: fecha_cuadro_basico
    fields:
        fechaInicioCuadroBasico:
            type: datetime
            nullable: false
            default: now
            column: fecha_inicio_cuadro_basico
    oneToOne:
        insumo:
            targetEntity: CtlInsumo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                insumo_id:
                    referencedColumnName: id
            orphanRemoval: false
        establecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                establecimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
