Minsal\CoreBundle\Entity\MntCierre:
    type: entity
    table: mnt_cierre
    indexes:
        IDX_CFABE6D071B61351:
            columns:
                - establecimiento_id
        IDX_CFABE6D09E59795B:
            columns:
                - user_id_schema
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaCierre:
            type: datetime
            nullable: true
            column: fecha_cierre
        ctlInsumo:
            type: bigint
            nullable: false
            unsigned: false
            column: ctl_insumo
        userIpSchema:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '::1'
            column: user_ip_schema
        registroSchema:
            type: datetime
            nullable: false
            default: now
            column: registro_schema
    manyToOne:
        establecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                establecimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
        userSchema:
            targetEntity: FosUser
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id_schema:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
