Minsal\CoreBundle\Entity\MntCierre:
    type: entity
    table: mnt_cierre
    indexes:
        IDX_CFABE6D071B61351:
            columns:
                - establecimiento_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechaCierre:
            type: datetime
            nullable: true
            column: fecha_cierre
    manyToOne:
        establecimiento:
            targetEntity: CtlEstablecimiento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                establecimiento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
