admin_acceso_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:index" }
    methods:  GET

admin_acceso_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:show" }
    methods:  GET

admin_acceso_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:new" }
    methods:  [GET, POST]

admin_acceso_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:edit" }
    methods:  [GET, POST]

admin_acceso_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:delete" }
    methods:  DELETE
