admin_accesos_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:index" }
    methods:  GET

admin_accesos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:show" }
    methods:  GET

admin_accesos_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:new" }
    methods:  [GET, POST]

admin_accesos_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:edit" }
    methods:  [GET, POST]

admin_accesos_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlAcceso:delete" }
    methods:  DELETE
