componente_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:index" }
    methods:  GET

componente_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:show" }
    methods:  GET

componente_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:new" }
    methods:  [GET, POST]

componente_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:edit" }
    methods:  [GET, POST]

componente_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:delete" }
    methods:  DELETE
