consumo_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlConsumo:index" }
    methods:  GET

consumo_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlConsumo:show" }
    methods:  GET

consumo_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlConsumo:new" }
    methods:  [GET, POST]

consumo_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlConsumo:edit" }
    methods:  [GET, POST]

consumo_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlConsumo:delete" }
    methods:  DELETE
