configuracion_programas_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:index" }
    methods:  GET

configuracion_programas_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:show" }
    methods:  GET

configuracion_programas_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:new" }
    methods:  [GET, POST]

configuracion_programas_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:edit" }
    methods:  [GET, POST]

configuracion_programas_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlComponente:delete" }
    methods:  DELETE
