departamento_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlDepartamento:index" }
    methods:  GET

departamento_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlDepartamento:show" }
    methods:  GET



