existencias_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlExistencias:index" }
    methods:  GET

existencias_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlExistencias:show" }
    methods:  GET

existencias_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlExistencias:new" }
    methods:  [GET, POST]

existencias_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlExistencias:edit" }
    methods:  [GET, POST]

existencias_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlExistencias:delete" }
    methods:  DELETE
