configuracion_establecimientos_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlEstablecimiento:index" }
    methods:  [GET, POST]

configuracion_establecimientos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlEstablecimiento:show" }
    methods:  GET
    
configuracion_establecimientos_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlEstablecimiento:edit" }
    methods:  [GET, POST]

configuracion_establecimientos_cuadro:
    path:     /cuadrosbasicos
    defaults: { _controller: "MinsalCoreBundle:CtlEstablecimiento:cuadro" }
    methods:  [GET, POST]
configuracion_establecimientos_ajax:
    path:     /buscarajax
    defaults: { _controller: "MinsalCoreBundle:CtlEstablecimiento:ajax" }
    methods:  [GET|HEAD|POST]
    requirements:
        _method: POST|GET
