movimiento_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:index" }
    methods:  GET

movimiento_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:show" }
    methods:  GET

movimiento_new:
    path:     /new
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:new" }
    methods:  [GET, POST]

movimiento_edit:
    path:     /{id}/edit
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:edit" }
    methods:  [GET, POST]

movimiento_delete:
    path:     /{id}/delete
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:delete" }
    methods:  DELETE
    
movimiento_ajax:
    path:     /buscarajax
    defaults: { _controller: "MinsalCoreBundle:CtlMovimiento:ajax" }
    methods:  [GET|HEAD|POST]
    requirements:
        _method: POST|GET
