configuracion_mecanismos_index:
    path:     /
    defaults: { _controller: "MinsalCoreBundle:CtlMecanismo:index" }
    methods:  GET

configuracion_mecanismos_show:
    path:     /{id}/show
    defaults: { _controller: "MinsalCoreBundle:CtlMecanismo:show" }
    methods:  GET



