#Configuracion
minsal_core_registro_accesos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlmovimiento.yml"
    prefix:   /registro/movimientos
minsal_core_admin_accesos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlacceso.yml"
    prefix:   /admin/accesos
minsal_core_configuracion_suministros:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlsuministro.yml"
    prefix:   /configuracion/suministros
minsal_core_configuracion_tipoestablecimientos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctltipoestablecimiento.yml"
    prefix:   /configuracion/tipoestablecimientos
minsal_core_configuracion_productos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlinsumo.yml"
    prefix:   /configuracion/productos
minsal_core_configuracion_mecanismos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlmecanismo.yml"
    prefix:   /configuracion/mecanismos
minsal_core_configuracion_programas:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlcomponente.yml"
    prefix:   /configuracion/programas
minsal_core_configuracion_establecimientos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlestablecimiento.yml"
    prefix:   /configuracion/establecimientos
#Administracion
minsal_core_admin_personas:
    resource: "@MinsalCoreBundle/Resources/config/routing/fosuser.yml"
    prefix:   /admin/personas
minsal_core_admin_rol:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlrol.yml"
    prefix:   /admin/rol
#Registro
minsal_core_homepage:
    path:     /
    defaults: { _controller: MinsalCoreBundle:Default:index }
minsal_core_registro_index:
    path:     /registro/index
    defaults: { _controller: MinsalCoreBundle:Default:registro }
minsal_core_registro_manual:
    path:     /registro/manual
    defaults: { _controller: MinsalCoreBundle:Default:manual }
    methods:  [GET|HEAD|POST]
    requirements:
        _method: POST|GET
minsal_core_registro_archivo:
    path:     /registro/archivo
    defaults: { _controller: MinsalCoreBundle:Default:archivo }
    methods:  [GET, POST]
minsal_core_registro_archivo_xls:
    path:     /registro/archivo_xls
    defaults: { _controller: MinsalRutinaBundle:Default:xls }


minsal_core_configuracion_cuadro:
    path:     /configuracion/cuadrosbasicos
    defaults: { _controller: MinsalCoreBundle:Default:cuadro }
    methods:  [GET, POST]

minsal_core_configuracion_cuadro_del:
    path:     /configuracion/delcuadrosbasicos
    defaults: { _controller: MinsalCoreBundle:CtlEstablecimiento:delcuadro }
    methods:  [GET|HEAD|POST]
    requirements:
        _method: POST|GET

minsal_core_configuracion_cierre:
    path:     /configuracion/movimientos_cierre
    defaults: { _controller: MinsalCoreBundle:CtlMovimiento:cierre }
    methods:  [GET|HEAD|POST]
    requirements:
        _method: POST|GET
