minsal_core_admin_rol:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlrol.yml"
    prefix:   /admin/rol
minsal_core_configuracion_establecimientos:
    resource: "@MinsalCoreBundle/Resources/config/routing/ctlestablecimiento.yml"
    prefix:   /configuracion/establecimientos
minsal_core_admin_personas:
    resource: "@MinsalCoreBundle/Resources/config/routing/fosuser.yml"
    prefix:   /admin/personas

minsal_core_homepage:
    path:     /
    defaults: { _controller: MinsalCoreBundle:Default:index }
minsal_core_registro_index:
    path:     /registro/index
    defaults: { _controller: MinsalCoreBundle:Default:registro }
minsal_core_registro_manual:
    path:     /registro/manual
    defaults: { _controller: MinsalCoreBundle:Default:manual }
minsal_core_registro_archivo:
    path:     /registro/archivo
    defaults: { _controller: MinsalCoreBundle:Default:archivo }


minsal_core_configuracion_cuadro:
    path:     /configuracion/cuadrosbasicos
    defaults: { _controller: MinsalCoreBundle:Default:cuadro }
    methods:  [GET, POST]
